/**
 * LumenTale Wiki — canonical、OG、Twitter、sitemap 使用此域名。
 */
export const seoConfig = {
  domain: 'lumentale.org',
  fullDomain: 'https://lumentale.org',
  siteName: 'LumenTale Wiki',
  /** Site logo — header, footer, OG/Twitter, JSON-LD */
  defaultOgImage: '/images/logo.webp',
  defaults: {
    title: 'LumenTale | Animon, Starters, Evolutions, Wiki & Guides',
    description:
      'LumenTale guides for Memories of Trey — Animon dex, starter picks, affinity chart, evolution routes, skills, items, Fountain recipes, boss fights, and the Talea map for your run.',
    keywords:
      'LumenTale, Memories of Trey, LumenTale Animon, LumenTale guide, Talea wiki, LumenTale recipes',
    author: 'LumenTale Wiki',
    type: 'website',
  },
  priorities: {
    home: 1.0,
    animon: 0.95,
    'animon-detail': 0.75,
    beginner: 0.92,
    starters: 0.9,
    affinities: 0.88,
    evolutions: 0.88,
    guides: 0.9,
    'guide-detail': 0.8,
    map: 0.85,
    wiki: 0.9,
    'wiki-skills': 0.85,
    'wiki-items': 0.85,
    'wiki-item-detail': 0.72,
    'wiki-bosses': 0.85,
    'wiki-cooking': 0.85,
    'wiki-crafting': 0.85,
    search: 0.8,
    'wiki-recipe-detail': 0.72,
    'legal-privacy': 0.35,
    'legal-terms': 0.35,
    'legal-copyright': 0.35,
    'legal-about': 0.45,
    'legal-contact': 0.45,
  },
  changefreq: {
    home: 'weekly',
    animon: 'weekly',
    'animon-detail': 'monthly',
    beginner: 'weekly',
    starters: 'weekly',
    affinities: 'weekly',
    evolutions: 'weekly',
    guides: 'weekly',
    'guide-detail': 'monthly',
    map: 'weekly',
    wiki: 'weekly',
    'wiki-skills': 'weekly',
    'wiki-items': 'weekly',
    'wiki-item-detail': 'monthly',
    'wiki-bosses': 'weekly',
    'wiki-cooking': 'weekly',
    'wiki-crafting': 'weekly',
    search: 'weekly',
    'wiki-recipe-detail': 'monthly',
    'legal-privacy': 'yearly',
    'legal-terms': 'yearly',
    'legal-copyright': 'yearly',
    'legal-about': 'yearly',
    'legal-contact': 'yearly',
  },
}
